# Generated by Django 4.2.7 on 2026-06-11 19:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'تصنيف منتج',
                'verbose_name_plural': 'تصنيفات المنتجات',
                'db_table': 'product_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='الرمز SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر البيع')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='التكلفة')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='المخزون')),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=10, verbose_name='حد التنبيه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('show_in_store', models.BooleanField(default=True, verbose_name='يظهر في المتجر')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='التصنيف')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
    ]
