# Generated by Django 4.2.7 on 2026-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('purchase', 'شراء'), ('sale', 'بيع'), ('adjustment', 'تعديل'), ('transfer', 'نقل')], max_length=20, verbose_name='النوع'),
        ),
    ]
