# Generated by Django 4.2.7 on 2026-06-13 05:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings_work_days'),
        ('products', '0003_alter_stockmovement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='الرقم')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='المورد')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة/بنك'), ('credit', 'آجل')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'فاتورة مشتريات',
                'verbose_name_plural': 'فواتير المشتريات',
                'db_table': 'purchase_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='products.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='products.product')),
            ],
            options={
                'db_table': 'purchase_invoice_lines',
            },
        ),
    ]
