# Generated by Django 4.2.7 on 2026-06-14 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_purchase_paid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
    ]
