# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_use_localdate_for_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المخزون'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الإجمالي'),
        ),
    ]
