# Generated by Django 4.2.7 on 2026-06-14 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_ordering_stockmovement_reversal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='المخزون'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='تكلفة الوحدة'),
        ),
    ]
