# Generated by Django 4.2.7 on 2026-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_center_alter_productcategory_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='number',
            field=models.CharField(max_length=50, verbose_name='الرقم'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('center', 'number'), name='unique_purchase_number_per_center'),
        ),
    ]
