# Generated by Django 4.2.7 on 2026-06-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='التخصص')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='الصورة')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='اللون في التقويم')),
                ('work_start', models.TimeField(blank=True, null=True, verbose_name='بداية الدوام')),
                ('work_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الدوام')),
                ('working_days', models.JSONField(default=list, help_text='قائمة أرقام الأيام: 0=أحد ... 6=سبت', verbose_name='أيام العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
                ('services', models.ManyToManyField(blank=True, related_name='specialists', to='services.service', verbose_name='الخدمات المتخصصة')),
            ],
            options={
                'verbose_name': 'متخصص',
                'verbose_name_plural': 'الفريق',
                'db_table': 'specialists',
                'ordering': ['order', 'name'],
            },
        ),
    ]
