# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='order',
            field=models.PositiveIntegerField(verbose_name='الترتيب'),
        ),
    ]
