# Generated by Django 4.2.7 on 2026-06-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_specialist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]
