# Generated by Django 4.2.7 on 2026-06-14 22:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_specialist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الراتب الأساسي'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='نسبة العمولة %'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='salary_type',
            field=models.CharField(choices=[('fixed', 'راتب ثابت'), ('commission', 'نسبة عمولة'), ('both', 'ثابت + نسبة')], default='fixed', max_length=20, verbose_name='نوع الراتب'),
        ),
    ]
