# Generated by Django 4.2.7 on 2026-06-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_center_alter_user_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي'),
        ),
    ]
