# Generated by Django 4.2.7 on 2026-06-11 19:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('products', '0001_initial'),
        ('core', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('client_phone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('client_address', models.TextField(blank=True, verbose_name='عنوان التوصيل')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'مؤكد'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'طلب متجر',
                'verbose_name_plural': 'طلبات المتجر',
                'db_table': 'store_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإجمالي')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.storeorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'store_order_items',
            },
        ),
        migrations.CreateModel(
            name='OnlineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('client_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('preferred_date', models.DateField(verbose_name='التاريخ المفضل')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='الوقت المفضل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('new', 'جديد — بانتظار التأكيد'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_booking', to='appointments.appointment')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'verbose_name': 'حجز إلكتروني',
                'verbose_name_plural': 'الحجوزات الإلكترونية',
                'db_table': 'online_bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
