# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي'),
        ),
    ]
