# Generated by Django 4.2.7 on 2026-06-14 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_storeorder_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سعر الوحدة'),
        ),
    ]
