# Generated by Django 4.2.7 on 2026-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_package_price_alter_packageservice_order_and_more'),
        ('store', '0003_alter_storeorder_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='online_bookings', to='services.service', verbose_name='الخدمات'),
        ),
    ]
