# Generated by Django 4.2.7 on 2026-06-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_center'),
        ('store', '0005_alter_onlinebooking_center_alter_storeorder_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_bookings', to='clients.client', verbose_name='العميل'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_orders', to='clients.client', verbose_name='العميل'),
        ),
    ]
