# Generated by Django 4.2.7 on 2026-06-11 19:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('core', '0001_initial'),
        ('appointments', '0001_initial'),
        ('clients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='قبل الخصم')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='قيمة الخصم')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='المدفوع')),
                ('payment_method', models.CharField(choices=[('cash', 'نقد'), ('card', 'بطاقة'), ('transfer', 'تحويل'), ('wallet', 'محفظة إلكترونية')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('paid', 'مدفوعة'), ('partial', 'مدفوعة جزئياً'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='appointments.appointment', verbose_name='الموعد')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='خصم %')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإجمالي')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
            options={
                'db_table': 'invoice_lines',
            },
        ),
    ]
