# Generated by Django 4.2.7 on 2026-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card', 'بطاقة'), ('transfer', 'تحويل'), ('wallet', 'محفظة إلكترونية'), ('later', 'الدفع لاحقاً')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
