# Generated by Django 4.2.7 on 2026-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة أو بنك'), ('later', 'لاحقاً')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
