# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_use_localdate_for_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المدفوع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قبل الخصم'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الضريبة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='خصم %'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي'),
        ),
    ]
