# Generated by Django 4.2.7 on 2026-06-14 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='خصم %'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='سعر الوحدة'),
        ),
    ]
