# Generated by Django 4.2.7 on 2026-06-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_center_options_alter_servicetype_options_and_more'),
        ('billing', '0009_alter_invoiceline_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب'),
        ),
    ]
