# Generated by Django 4.2.7 on 2026-06-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_invoice_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=50, verbose_name='رقم الفاتورة'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('center', 'number'), name='unique_invoice_number_per_center'),
        ),
    ]
