# Generated by Django 4.2.7 on 2026-06-11 19:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الباقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الباقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('show_in_store', models.BooleanField(default=True, verbose_name='يظهر في المتجر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='الصورة')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'باقة',
                'verbose_name_plural': 'الباقات',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('icon', models.CharField(default='fas fa-spa', max_length=60, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#ec4899', max_length=7, verbose_name='اللون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'db_table': 'service_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='المدة (دقيقة)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='التكلفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('show_in_store', models.BooleanField(default=True, verbose_name='يظهر في المتجر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='الصورة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory', verbose_name='التصنيف')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'db_table': 'services',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_services', to='services.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'db_table': 'package_services',
                'ordering': ['order'],
                'unique_together': {('package', 'service')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(through='services.PackageService', to='services.service', verbose_name='الخدمات المضمّنة'),
        ),
    ]
