# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageservice',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='order',
            field=models.PositiveIntegerField(verbose_name='الترتيب'),
        ),
    ]
