# Generated by Django 4.2.7 on 2026-06-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings_work_days'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpayment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clientpayment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='treasury',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز'),
        ),
    ]
