# Generated by Django 4.2.7 on 2026-06-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_add_client'),
        ('finance', '0002_remove_clientpayment_created_at_and_more'),
    ]

    operations = [
    ]
