# Generated by Django 4.2.7 on 2026-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_expense_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة أو بنك')], default='cash', max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة أو بنك')], default='cash', max_length=50, verbose_name='طريقة الدفع'),
        ),
    ]
