# Generated by Django 4.2.7 on 2026-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_add_clientpayment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientpayment',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'دفعة عميل', 'verbose_name_plural': 'مدفوعات العملاء'},
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
    ]
