# Generated by Django 4.2.7 on 2026-06-14 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_clientpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
    ]
