# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_use_localdate_for_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد الابتدائي'),
        ),
    ]
