# Generated by Django 4.2.7 on 2026-06-14 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_models_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الرصيد الابتدائي'),
        ),
        migrations.AlterField(
            model_name='treasurymovement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='المبلغ'),
        ),
    ]
