# Generated by Django 4.2.7 on 2026-06-14 22:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_specialist_base_salary_specialist_commission_rate_and_more'),
        ('core', '0009_alter_centerbackup_file_size_alter_servicetype_order'),
        ('finance', '0012_alter_clientpayment_amount_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='من')),
                ('period_end', models.DateField(verbose_name='إلى')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الراتب الأساسي')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='العمولة')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الحوافز')),
                ('advances_deducted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='السلف المخصومة')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='خصومات أخرى')),
                ('deductions_notes', models.TextField(blank=True, verbose_name='تفاصيل الخصومات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('paid', 'مدفوع'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='staff.specialist', verbose_name='الفنية')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.treasury', verbose_name='الخزينة')),
            ],
            options={
                'verbose_name': 'كشف راتب',
                'verbose_name_plural': 'كشوف الرواتب',
                'db_table': 'salary_payments',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('pending', 'قائمة'), ('deducted', 'مخصومة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
                ('salary_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_items', to='finance.salarypayment', verbose_name='كشف الراتب')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='staff.specialist', verbose_name='الفنية')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.treasury', verbose_name='الخزينة')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
                'db_table': 'advances',
                'ordering': ['-created_at'],
            },
        ),
    ]
