# Generated by Django 4.2.7 on 2026-06-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_center_options_alter_servicetype_options_and_more'),
        ('finance', '0013_salarypayment_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='clientpayment',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب'),
        ),
    ]
