# Generated by Django 4.2.7 on 2026-06-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_specialist_center'),
        ('finance', '0014_alter_advance_center_alter_clientpayment_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='staff.specialist', verbose_name='مقدم الخدمة'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='staff.specialist', verbose_name='مقدم الخدمة'),
        ),
    ]
