# Generated by Django 4.2.7 on 2026-06-15 21:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_center_options_alter_servicetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0015_alter_advance_specialist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='من')),
                ('period_end', models.DateField(verbose_name='إلى')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الراتب الأساسي')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الحوافز')),
                ('advances_deducted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='السلف المخصومة')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='خصومات أخرى')),
                ('deductions_notes', models.TextField(blank=True, verbose_name='تفاصيل الخصومات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('paid', 'مدفوع'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.treasury', verbose_name='الخزينة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'كشف راتب موظف',
                'verbose_name_plural': 'كشوف رواتب الموظفين',
                'db_table': 'user_salary_payments',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('pending', 'قائمة'), ('deducted', 'مخصومة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب')),
                ('salary_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_items', to='finance.usersalarypayment', verbose_name='كشف الراتب')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.treasury', verbose_name='الخزينة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة موظف',
                'verbose_name_plural': 'سلف الموظفين',
                'db_table': 'user_advances',
                'ordering': ['-created_at'],
            },
        ),
    ]
