# Generated by Django 4.2.7 on 2026-06-16 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_center_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0005_alter_specialist_center'),
        ('finance', '0016_usersalarypayment_useradvance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('specialist', 'فريق الخدمة'), ('user', 'موظف')], default='specialist', max_length=20, verbose_name='نوع الشخص')),
                ('type', models.CharField(choices=[('bonus', 'حافز'), ('deduction', 'خصم')], default='bonus', max_length=20, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('payout', models.CharField(choices=[('immediate', 'فوري'), ('with_salary', 'مع الراتب')], default='with_salary', max_length=20, verbose_name='طريقة الصرف')),
                ('method', models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة أو بنك')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('paid', 'مدفوع'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='الحساب')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentives', to='staff.specialist', verbose_name='مقدم الخدمة')),
                ('treasury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.treasury', verbose_name='الخزينة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentives', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حافز أو خصم',
                'verbose_name_plural': 'الحوافز والخصومات',
                'db_table': 'incentives',
                'ordering': ['-created_at'],
            },
        ),
    ]
