# Generated by Django 4.2.7 on 2026-06-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_add_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='salary_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentive_items', to='finance.salarypayment', verbose_name='كشف الراتب'),
        ),
    ]
