# Generated by Django 4.2.7 on 2026-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_incentive_salary_payment_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة / بنك')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة / بنك')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='useradvance',
            name='method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة / بنك')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='usersalarypayment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card_or_bank', 'بطاقة / بنك')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
