# Generated by Django 4.2.7 on 2026-06-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_payment_method_to_salary_advance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ['-id'], 'verbose_name': 'كشف راتب', 'verbose_name_plural': 'كشوف الرواتب'},
        ),
        migrations.AlterModelOptions(
            name='usersalarypayment',
            options={'ordering': ['-id'], 'verbose_name': 'كشف راتب موظف', 'verbose_name_plural': 'كشوف رواتب الموظفين'},
        ),
    ]
