# Generated by Django 4.2.7 on 2026-06-11 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المركز')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط المختصر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='centers/logos/', verbose_name='الشعار')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='السودان', max_length=100, verbose_name='البلد')),
                ('plan', models.CharField(choices=[('trial', 'تجريبي'), ('starter', 'مبتدئ'), ('pro', 'احترافي'), ('enterprise', 'مؤسسات')], default='trial', max_length=20, verbose_name='الباقة')),
                ('plan_start', models.DateField(default=django.utils.timezone.now, verbose_name='بداية الاشتراك')),
                ('plan_expires', models.DateField(blank=True, null=True, verbose_name='نهاية الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_demo', models.BooleanField(default=False, verbose_name='حساب تجريبي')),
                ('timezone', models.CharField(default='Africa/Khartoum', max_length=50, verbose_name='المنطقة الزمنية')),
                ('currency', models.CharField(default='SDG', max_length=3, verbose_name='العملة')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('max_staff', models.IntegerField(default=10, verbose_name='عدد الموظفين')),
                ('max_users', models.IntegerField(default=5, verbose_name='عدد المستخدمين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مركز',
                'verbose_name_plural': 'المراكز',
                'db_table': 'centers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('icon', models.CharField(default='fas fa-spa', max_length=60, verbose_name='الأيقونة')),
                ('color', models.CharField(default='#ec4899', max_length=7, verbose_name='اللون')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'نوع المركز',
                'verbose_name_plural': 'أنواع المراكز',
                'db_table': 'service_types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_color', models.CharField(default='#ec4899', max_length=7, verbose_name='لون الفواتير')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10, verbose_name='بادئة الفاتورة')),
                ('invoice_next_number', models.PositiveIntegerField(default=1, verbose_name='الرقم التالي')),
                ('invoice_footer', models.TextField(blank=True, verbose_name='تذييل الفاتورة')),
                ('show_tax_on_invoice', models.BooleanField(default=False, verbose_name='إظهار الضريبة')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة %')),
                ('booking_enabled', models.BooleanField(default=True, verbose_name='الحجز الذاتي عبر المتجر')),
                ('booking_advance_days', models.IntegerField(default=30, verbose_name='أقصى حجز مسبق (يوم)')),
                ('slot_minutes', models.IntegerField(default=30, verbose_name='مدة الفترة الزمنية (دقيقة)')),
                ('work_start', models.TimeField(blank=True, null=True, verbose_name='بداية الدوام')),
                ('work_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الدوام')),
                ('store_enabled', models.BooleanField(default=False, verbose_name='تفعيل المتجر الإلكتروني')),
                ('store_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المتجر')),
                ('store_cover', models.ImageField(blank=True, null=True, upload_to='store/', verbose_name='صورة غلاف المتجر')),
                ('loyalty_enabled', models.BooleanField(default=False, verbose_name='تفعيل نقاط الولاء')),
                ('points_per_currency', models.IntegerField(default=1, verbose_name='نقاط لكل وحدة نقد')),
                ('reminder_enabled', models.BooleanField(default=False, verbose_name='تفعيل التذكير')),
                ('reminder_hours_before', models.IntegerField(default=24, verbose_name='تذكير قبل الموعد بـ (ساعة)')),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'إعدادات',
                'verbose_name_plural': 'إعدادات',
                'db_table': 'center_settings',
            },
        ),
        migrations.AddField(
            model_name='center',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='core.servicetype', verbose_name='نوع المركز'),
        ),
    ]
