# Generated by Django 4.2.7 on 2026-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settings_work_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='country',
            field=models.CharField(default='SD', max_length=10, verbose_name='البلد (كود)'),
        ),
    ]
