# Generated by Django 4.2.7 on 2026-06-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_center_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appointment_new', 'موعد جديد'), ('appointment_status', 'تحديث موعد'), ('invoice_paid', 'فاتورة مدفوعة'), ('invoice_new', 'فاتورة جديدة'), ('booking_new', 'حجز أونلاين'), ('stock_low', 'مخزون منخفض'), ('client_new', 'عميل جديد'), ('payment_received', 'دفعة واردة')], max_length=50, verbose_name='النوع')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='رابط')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
