# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerbackup',
            name='file_size',
            field=models.BigIntegerField(verbose_name='الحجم بالبايت'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_new', 'حجز أونلاين'), ('order_new', 'طلب أونلاين'), ('stock_low', 'مخزون منخفض')], max_length=50, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='order',
            field=models.PositiveIntegerField(verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
    ]
