# Generated by Django 4.2.7 on 2026-06-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_work_schedule_and_closed_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
    ]
