# Generated by Django 4.2.7 on 2026-06-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_settings_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerbackup',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='الحجم بالبايت'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]
