# Generated by Django 4.2.7 on 2026-06-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_support_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['-created_at'], 'verbose_name': 'حساب', 'verbose_name_plural': 'الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'نوع الحساب', 'verbose_name_plural': 'أنواع الحسابات'},
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الحساب'),
        ),
        migrations.AlterField(
            model_name='center',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='core.servicetype', verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='centerbackup',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.center', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.center', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender_type',
            field=models.CharField(choices=[('center', 'الحساب'), ('admin', 'المشرف')], max_length=10, verbose_name='نوع المرسل'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='core.center', verbose_name='الحساب'),
        ),
    ]
