# Generated by Django 4.2.7 on 2026-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_center_options_alter_servicetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='plan',
            field=models.CharField(choices=[('trial', 'تجريبي'), ('starter', 'أساسي'), ('pro', 'متقدم'), ('enterprise', 'بريميوم')], default='trial', max_length=20, verbose_name='الباقة'),
        ),
    ]
