# Generated by Django 4.2.7 on 2026-06-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_center_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('maintenance_message', models.TextField(blank=True, default='النظام قيد الصيانة حالياً. سنعود قريباً.', verbose_name='رسالة الصيانة')),
                ('announcement_active', models.BooleanField(default=False, verbose_name='تفعيل الإشعار')),
                ('announcement_text', models.CharField(blank=True, max_length=500, verbose_name='نص الإشعار')),
                ('announcement_type', models.CharField(choices=[('info', 'معلوماتي'), ('warning', 'تحذير'), ('success', 'نجاح'), ('danger', 'خطر')], default='info', max_length=10, verbose_name='نوع الإشعار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'db_table': 'platform_settings',
            },
        ),
    ]
