# Generated by Django 4.2.7 on 2026-06-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('gender', models.CharField(choices=[('f', 'أنثى'), ('m', 'ذكر')], default='f', max_length=5, verbose_name='الجنس')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('referral', models.CharField(blank=True, choices=[('walk_in', 'زيارة مباشرة'), ('referral', 'توصية'), ('social', 'وسائل التواصل'), ('website', 'الموقع الإلكتروني'), ('other', 'أخرى')], max_length=20, verbose_name='مصدر التعريف')),
                ('points', models.IntegerField(default=0, verbose_name='نقاط الولاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'db_table': 'clients',
                'ordering': ['name'],
                'unique_together': {('center', 'phone')},
            },
        ),
    ]
