# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='points',
            field=models.IntegerField(verbose_name='نقاط الولاء'),
        ),
    ]
