# Generated by Django 4.2.7 on 2026-06-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='points',
            field=models.IntegerField(default=0, verbose_name='نقاط الولاء'),
        ),
    ]
