"""
Arab-world country → timezone / currency / phone-prefix mapping.
Used by registration and sysadmin center forms.
"""

ARAB_COUNTRIES = {
    'SA': {
        'name': 'المملكة العربية السعودية',
        'timezone': 'Asia/Riyadh',
        'currency': 'SAR',
        'currency_symbol': 'ر.س',
        'phone_prefix': '+966',
    },
    'AE': {
        'name': 'الإمارات العربية المتحدة',
        'timezone': 'Asia/Dubai',
        'currency': 'AED',
        'currency_symbol': 'د.إ',
        'phone_prefix': '+971',
    },
    'KW': {
        'name': 'الكويت',
        'timezone': 'Asia/Kuwait',
        'currency': 'KWD',
        'currency_symbol': 'د.ك',
        'phone_prefix': '+965',
    },
    'BH': {
        'name': 'البحرين',
        'timezone': 'Asia/Bahrain',
        'currency': 'BHD',
        'currency_symbol': 'د.ب',
        'phone_prefix': '+973',
    },
    'QA': {
        'name': 'قطر',
        'timezone': 'Asia/Qatar',
        'currency': 'QAR',
        'currency_symbol': 'ر.ق',
        'phone_prefix': '+974',
    },
    'OM': {
        'name': 'عُمان',
        'timezone': 'Asia/Muscat',
        'currency': 'OMR',
        'currency_symbol': 'ر.ع',
        'phone_prefix': '+968',
    },
    'YE': {
        'name': 'اليمن',
        'timezone': 'Asia/Aden',
        'currency': 'YER',
        'currency_symbol': 'ر.ي',
        'phone_prefix': '+967',
    },
    'JO': {
        'name': 'الأردن',
        'timezone': 'Asia/Amman',
        'currency': 'JOD',
        'currency_symbol': 'د.ا',
        'phone_prefix': '+962',
    },
    'LB': {
        'name': 'لبنان',
        'timezone': 'Asia/Beirut',
        'currency': 'LBP',
        'currency_symbol': 'ل.ل',
        'phone_prefix': '+961',
    },
    'SY': {
        'name': 'سوريا',
        'timezone': 'Asia/Damascus',
        'currency': 'SYP',
        'currency_symbol': 'ل.س',
        'phone_prefix': '+963',
    },
    'IQ': {
        'name': 'العراق',
        'timezone': 'Asia/Baghdad',
        'currency': 'IQD',
        'currency_symbol': 'د.ع',
        'phone_prefix': '+964',
    },
    'EG': {
        'name': 'مصر',
        'timezone': 'Africa/Cairo',
        'currency': 'EGP',
        'currency_symbol': 'ج.م',
        'phone_prefix': '+20',
    },
    'LY': {
        'name': 'ليبيا',
        'timezone': 'Africa/Tripoli',
        'currency': 'LYD',
        'currency_symbol': 'د.ل',
        'phone_prefix': '+218',
    },
    'TN': {
        'name': 'تونس',
        'timezone': 'Africa/Tunis',
        'currency': 'TND',
        'currency_symbol': 'د.ت',
        'phone_prefix': '+216',
    },
    'DZ': {
        'name': 'الجزائر',
        'timezone': 'Africa/Algiers',
        'currency': 'DZD',
        'currency_symbol': 'د.ج',
        'phone_prefix': '+213',
    },
    'MA': {
        'name': 'المغرب',
        'timezone': 'Africa/Casablanca',
        'currency': 'MAD',
        'currency_symbol': 'د.م',
        'phone_prefix': '+212',
    },
    'MR': {
        'name': 'موريتانيا',
        'timezone': 'Africa/Nouakchott',
        'currency': 'MRU',
        'currency_symbol': 'أ.م',
        'phone_prefix': '+222',
    },
    'SD': {
        'name': 'السودان',
        'timezone': 'Africa/Khartoum',
        'currency': 'SDG',
        'currency_symbol': 'ج.س',
        'phone_prefix': '+249',
    },
    'SO': {
        'name': 'الصومال',
        'timezone': 'Africa/Mogadishu',
        'currency': 'SOS',
        'currency_symbol': 'ش.ص',
        'phone_prefix': '+252',
    },
    'DJ': {
        'name': 'جيبوتي',
        'timezone': 'Africa/Djibouti',
        'currency': 'DJF',
        'currency_symbol': 'ف.ج',
        'phone_prefix': '+253',
    },
    'KM': {
        'name': 'جزر القمر',
        'timezone': 'Indian/Comoro',
        'currency': 'KMF',
        'currency_symbol': 'ف.ق',
        'phone_prefix': '+269',
    },
    'PS': {
        'name': 'فلسطين',
        'timezone': 'Asia/Gaza',
        'currency': 'ILS',
        'currency_symbol': '₪',
        'phone_prefix': '+970',
    },
}

# Ordered list for dropdowns — Gulf first (primary market), then Levant, then Africa
COUNTRY_CHOICES = [
    ('', 'اختر الدولة...'),
    ('SD', 'السودان'),
    ('EG', 'مصر'),
    ('SA', 'المملكة العربية السعودية'),
    ('AE', 'الإمارات العربية المتحدة'),
    ('KW', 'الكويت'),
    ('QA', 'قطر'),
    ('BH', 'البحرين'),
    ('OM', 'عُمان'),
    ('YE', 'اليمن'),
    ('JO', 'الأردن'),
    ('PS', 'فلسطين'),
    ('LB', 'لبنان'),
    ('SY', 'سوريا'),
    ('IQ', 'العراق'),
    ('LY', 'ليبيا'),
    ('TN', 'تونس'),
    ('DZ', 'الجزائر'),
    ('MA', 'المغرب'),
    ('MR', 'موريتانيا'),
    ('SO', 'الصومال'),
    ('DJ', 'جيبوتي'),
    ('KM', 'جزر القمر'),
]
