# Generated by Django 4.2.7 on 2026-06-11 19:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.TimeField(verbose_name='وقت البدء')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('in_progress', 'جارٍ التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='إجمالي السعر')),
                ('walk_in_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الزائر')),
                ('walk_in_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف الزائر')),
                ('source', models.CharField(choices=[('direct', 'مباشر'), ('store', 'المتجر'), ('phone', 'هاتف')], default='direct', max_length=20, verbose_name='مصدر الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.center', verbose_name='المركز')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client', verbose_name='العميل')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.package', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'المواعيد',
                'db_table': 'appointments',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='appointments.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.specialist')),
            ],
            options={
                'db_table': 'appointment_services',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, through='appointments.AppointmentService', to='services.service', verbose_name='الخدمات'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='staff.specialist', verbose_name='الفنية/الفني'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['center', 'date'], name='appointment_center__38a218_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['center', 'status'], name='appointment_center__e39509_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['center', 'date', 'status'], name='appointment_center__7b146a_idx'),
        ),
    ]
