# Generated by Django 4.2.7 on 2026-06-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي السعر'),
        ),
    ]
