# Generated by Django 4.2.7 on 2026-06-14 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='إجمالي السعر'),
        ),
        migrations.AlterField(
            model_name='appointmentservice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='السعر'),
        ),
    ]
