# Generated by Django 4.2.7 on 2026-06-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_specialist_center'),
        ('appointments', '0005_alter_appointment_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='staff.specialist', verbose_name='مقدم الخدمة'),
        ),
    ]
